name: eec_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: '>=2.19.2 <3.0.0'
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    easy_localization: ^3.0.1
    equatable: ^2.0.5
    flutter_riverpod: ^2.2.0
    freezed_annotation: ^2.2.0
    intl: ^0.17.0
    json_annotation: ^4.8.0
    logger: ^1.1.0
    path_provider: ^2.0.12
    go_router: ^6.0.6
    dio: ^5.0.0
    data_table_2: ^2.3.12
    file_picker: ^5.2.5
    csv: ^5.0.1
    share_plus: ^6.3.1
    web_socket_channel: ^2.3.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0
    build_runner: ^2.3.3
    freezed: ^2.3.2
    json_serializable: ^6.6.1
    riverpod_lint: ^1.0.1
    custom_lint: ^0.2.5

flutter:
    uses-material-design: true

    assets:
        - assets/langs/
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
